apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudknight
  labels:
    app: cloudknight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudknight
  template:
    metadata:
      labels:
        app: cloudknight
    spec:
      containers:
        - name: cloudknight
          image: cloudopsknight/cloudknight:d6f25d30fb79c04dfc42e0f7455e4483d1d19042
          ports:
            - containerPort: 8080
