apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudknight
  labels:
    app: cloudknight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudknight
  template:
    metadata:
      labels:
        app: cloudknight
    spec:
      containers:
        - name: cloudknight
          image: cloudopsknight/cloudknight:74513a25c1bcc2da86b7067a5f69e8ef6e83e845
          ports:
            - containerPort: 8080
